
package com.liuxiangwin.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IService", targetNamespace = "http://service.webservice.liuxiangwin.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param machineId
     * @return
     *     returns com.liuxiangwin.webservice.client.Meter
     */
    @WebMethod
    @WebResult(name = "adjustResult", targetNamespace = "")
    @RequestWrapper(localName = "adjustment", targetNamespace = "http://service.webservice.liuxiangwin.com/", className = "com.liuxiangwin.webservice.client.Adjustment")
    @ResponseWrapper(localName = "adjustmentResponse", targetNamespace = "http://service.webservice.liuxiangwin.com/", className = "com.liuxiangwin.webservice.client.AdjustmentResponse")
    public Meter adjustment(
        @WebParam(name = "machineId", targetNamespace = "")
        String machineId);

    /**
     * 
     * @param seCondition
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "searchResult", targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://service.webservice.liuxiangwin.com/", className = "com.liuxiangwin.webservice.client.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://service.webservice.liuxiangwin.com/", className = "com.liuxiangwin.webservice.client.SearchResponse")
    public String search(
        @WebParam(name = "seCondition", targetNamespace = "")
        String seCondition);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "entry", targetNamespace = "http://service.webservice.liuxiangwin.com/", className = "com.liuxiangwin.webservice.client.Entry")
    @ResponseWrapper(localName = "entryResponse", targetNamespace = "http://service.webservice.liuxiangwin.com/", className = "com.liuxiangwin.webservice.client.EntryResponse")
    public String entry(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
